# Generated by Django 2.2 on 2020-05-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='action',
        ),
        migrations.RemoveField(
            model_name='item',
            name='comedy',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='item',
            name='electronic',
        ),
        migrations.RemoveField(
            model_name='item',
            name='scifi',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(related_name='category', to='store_app.Item')),
            ],
        ),
    ]
