# Generated by Django 2.2 on 2020-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20200529_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='items', to='store_app.User'),
        ),
    ]
