# Generated by Django 2.2 on 2020-05-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20200529_0245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
